USE [master]
GO

/****** Object:  Database [BlinkyDB]    Script Date: 18/03/2019 10:33:33 ******/
CREATE DATABASE [BlinkyDB]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'BlinkyDB', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.SQLEXPRESS\MSSQL\DATA\BlinkyDB.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'BlinkyDB_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.SQLEXPRESS\MSSQL\DATA\BlinkyDB_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

ALTER DATABASE [BlinkyDB] SET COMPATIBILITY_LEVEL = 140
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [BlinkyDB].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [BlinkyDB] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [BlinkyDB] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [BlinkyDB] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [BlinkyDB] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [BlinkyDB] SET ARITHABORT OFF 
GO

ALTER DATABASE [BlinkyDB] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [BlinkyDB] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [BlinkyDB] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [BlinkyDB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [BlinkyDB] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [BlinkyDB] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [BlinkyDB] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [BlinkyDB] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [BlinkyDB] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [BlinkyDB] SET  DISABLE_BROKER 
GO

ALTER DATABASE [BlinkyDB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [BlinkyDB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [BlinkyDB] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [BlinkyDB] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [BlinkyDB] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [BlinkyDB] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [BlinkyDB] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [BlinkyDB] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [BlinkyDB] SET  MULTI_USER 
GO

ALTER DATABASE [BlinkyDB] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [BlinkyDB] SET DB_CHAINING OFF 
GO

ALTER DATABASE [BlinkyDB] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [BlinkyDB] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [BlinkyDB] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [BlinkyDB] SET QUERY_STORE = OFF
GO

ALTER DATABASE [BlinkyDB] SET  READ_WRITE 
GO

