#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 4.21
#  in conjunction with Tcl version 8.6
#    Mar 09, 2019 07:45:35 PM +0200  platform: Windows NT

import sys

try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk
import LogicGui
from functools import partial
try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

def set_Tk_var():
    global combobox
    combobox = tk.StringVar()

def init(top, gui, *args, **kwargs):
    global w, top_level, root
    w = gui
    top_level = top
    root = top

w = None

def create_AdminPanel(root, *args, **kwargs):
    '''Starting point when module is imported by another program.'''
    global w, w_win, rt
    rt = root
    w = tk.Toplevel (root)
    set_Tk_var()
    top = AdminPanel (w)
    init(w, top, *args, **kwargs)
    return (w, top)

def destroy_AdminPanel():
    global w
    w.destroy()
    w = None

class AdminPanel:
    def create_AdminPanelWin(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85'
        _ana2color = '#ececec' # Closest X11 color: 'gray92'
        self.style = ttk.Style()
        if sys.platform == "win32":
            self.style.theme_use('winnative')
        self.style.configure('.',background=_bgcolor)
        self.style.configure('.',foreground=_fgcolor)
        self.style.configure('.',font="TkDefaultFont")
        self.style.map('.',background=
            [('selected', _compcolor), ('active',_ana2color)])

        top.geometry("1162x848+446+87")
        top.title("New Toplevel")
        top.configure(background="#d9d9d9")
        top.configure(highlightbackground="#d9d9d9")
        top.configure(highlightcolor="black")

        self.AdminOptions = tk.Frame(top)
        self.AdminOptions.place(relx=0.155, rely=0.024, relheight=0.943
                , relwidth=0.688)
        self.AdminOptions.configure(relief='groove')
        self.AdminOptions.configure(borderwidth="2")
        self.AdminOptions.configure(relief='groove')
        self.AdminOptions.configure(background="#d9d9d9")
        self.AdminOptions.configure(highlightbackground="#d9d9d9")
        self.AdminOptions.configure(highlightcolor="black")
        self.AdminOptions.configure(width=125)

        self.AdminCtlPanel = tk.Label(self.AdminOptions)
        self.AdminCtlPanel.place(relx=0.294, rely=0.0, height=81, width=317)
        self.AdminCtlPanel.configure(activebackground="#f9f9f9")
        self.AdminCtlPanel.configure(activeforeground="black")
        self.AdminCtlPanel.configure(background="#d9d9d9")
        self.AdminCtlPanel.configure(disabledforeground="#a3a3a3")
        self.AdminCtlPanel.configure(font="-family {Segoe UI} -size 14")
        self.AdminCtlPanel.configure(foreground="#000000")
        self.AdminCtlPanel.configure(highlightbackground="#d9d9d9")
        self.AdminCtlPanel.configure(highlightcolor="black")
        self.AdminCtlPanel.configure(text='''Admin Control Panel''')

        self.AddOrRmvMentorStat = tk.Label(self.AdminOptions)
        self.AddOrRmvMentorStat.place(relx=0.05, rely=0.088, height=51
                , width=317)
        self.AddOrRmvMentorStat.configure(activebackground="#f9f9f9")
        self.AddOrRmvMentorStat.configure(activeforeground="black")
        self.AddOrRmvMentorStat.configure(background="#d9d9d9")
        self.AddOrRmvMentorStat.configure(disabledforeground="#a3a3a3")
        self.AddOrRmvMentorStat.configure(font="-family {Segoe UI} -size 11")
        self.AddOrRmvMentorStat.configure(foreground="#000000")
        self.AddOrRmvMentorStat.configure(highlightbackground="#d9d9d9")
        self.AddOrRmvMentorStat.configure(highlightcolor="black")
        self.AddOrRmvMentorStat.configure(text='''Add or Remove Mentor Status:''')

        self.EnterUserID = tk.Label(self.AdminOptions)
        self.EnterUserID.place(relx=0.038, rely=0.15, height=31, width=137)
        self.EnterUserID.configure(activebackground="#f9f9f9")
        self.EnterUserID.configure(activeforeground="black")
        self.EnterUserID.configure(background="#d9d9d9")
        self.EnterUserID.configure(disabledforeground="#a3a3a3")
        self.EnterUserID.configure(foreground="#000000")
        self.EnterUserID.configure(highlightbackground="#d9d9d9")
        self.EnterUserID.configure(highlightcolor="black")
        self.EnterUserID.configure(text='''Choose User ID:''')

        self.AddNewMentorBtn = tk.Button(self.AdminOptions)
        self.AddNewMentorBtn.place(relx=0.563, rely=0.156, height=32, width=148)
        self.AddNewMentorBtn.configure(activebackground="#ececec")
        self.AddNewMentorBtn.configure(activeforeground="#000000")
        self.AddNewMentorBtn.configure(background="#d9d9d9")
        self.AddNewMentorBtn.configure(disabledforeground="#a3a3a3")
        self.AddNewMentorBtn.configure(foreground="#000000")
        self.AddNewMentorBtn.configure(highlightbackground="#d9d9d9")
        self.AddNewMentorBtn.configure(highlightcolor="black")
        self.AddNewMentorBtn.configure(pady="0")
        self.AddNewMentorBtn.configure(text='''Press to Add''')

        self.TSeparator1 = ttk.Separator(self.AdminOptions)
        self.TSeparator1.place(relx=-0.013, rely=0.269, relwidth=1.013)

        self.RmvMentorBtn = tk.Button(self.AdminOptions)
        self.RmvMentorBtn.place(relx=0.775, rely=0.156, height=32, width=148)
        self.RmvMentorBtn.configure(activebackground="#ececec")
        self.RmvMentorBtn.configure(activeforeground="#000000")
        self.RmvMentorBtn.configure(background="#d9d9d9")
        self.RmvMentorBtn.configure(disabledforeground="#a3a3a3")
        self.RmvMentorBtn.configure(foreground="#000000")
        self.RmvMentorBtn.configure(highlightbackground="#d9d9d9")
        self.RmvMentorBtn.configure(highlightcolor="black")
        self.RmvMentorBtn.configure(pady="0")
        self.RmvMentorBtn.configure(text='''Press to Remove''')

        self.AddRmvImgsLabel = tk.Label(self.AdminOptions)
        self.AddRmvImgsLabel.place(relx=0.044, rely=0.275, height=51, width=257)
        self.AddRmvImgsLabel.configure(activebackground="#f9f9f9")
        self.AddRmvImgsLabel.configure(activeforeground="black")
        self.AddRmvImgsLabel.configure(background="#d9d9d9")
        self.AddRmvImgsLabel.configure(disabledforeground="#a3a3a3")
        self.AddRmvImgsLabel.configure(font="-family {Segoe UI} -size 11")
        self.AddRmvImgsLabel.configure(foreground="#000000")
        self.AddRmvImgsLabel.configure(highlightbackground="#d9d9d9")
        self.AddRmvImgsLabel.configure(highlightcolor="black")
        self.AddRmvImgsLabel.configure(text='''Add or Remove Images:''')

        self.ChooseImageAddLab = tk.Label(self.AdminOptions)
        self.ChooseImageAddLab.place(relx=0.063, rely=0.344, height=31
                , width=183)
        self.ChooseImageAddLab.configure(activebackground="#f9f9f9")
        self.ChooseImageAddLab.configure(activeforeground="black")
        self.ChooseImageAddLab.configure(background="#d9d9d9")
        self.ChooseImageAddLab.configure(disabledforeground="#a3a3a3")
        self.ChooseImageAddLab.configure(foreground="#000000")
        self.ChooseImageAddLab.configure(highlightbackground="#d9d9d9")
        self.ChooseImageAddLab.configure(highlightcolor="black")
        self.ChooseImageAddLab.configure(text='''Choose Image to add:''')

        self.EntryForChoosenImage = tk.Entry(self.AdminOptions)
        self.EntryForChoosenImage.place(relx=0.3, rely=0.35, height=26
                , relwidth=0.455)
        self.EntryForChoosenImage.configure(background="white")
        self.EntryForChoosenImage.configure(disabledforeground="#a3a3a3")
        self.EntryForChoosenImage.configure(font="TkFixedFont")
        self.EntryForChoosenImage.configure(foreground="#000000")
        self.EntryForChoosenImage.configure(highlightbackground="#d9d9d9")
        self.EntryForChoosenImage.configure(highlightcolor="black")
        self.EntryForChoosenImage.configure(insertbackground="black")
        self.EntryForChoosenImage.configure(selectbackground="#c4c4c4")
        self.EntryForChoosenImage.configure(selectforeground="black")

        self.SearchForImageBtn = tk.Button(self.AdminOptions)
        self.SearchForImageBtn.place(relx=0.788, rely=0.35, height=32, width=118)

        self.SearchForImageBtn.configure(activebackground="#ececec")
        self.SearchForImageBtn.configure(activeforeground="#000000")
        self.SearchForImageBtn.configure(background="#d9d9d9")
        self.SearchForImageBtn.configure(disabledforeground="#a3a3a3")
        self.SearchForImageBtn.configure(foreground="#000000")
        self.SearchForImageBtn.configure(highlightbackground="#d9d9d9")
        self.SearchForImageBtn.configure(highlightcolor="black")
        self.SearchForImageBtn.configure(pady="0")
        self.SearchForImageBtn.configure(text='''Search...''')

        self.RmvImageIdLabel = tk.Label(self.AdminOptions)
        self.RmvImageIdLabel.place(relx=0.063, rely=0.45, height=31, width=240)
        self.RmvImageIdLabel.configure(activebackground="#f9f9f9")
        self.RmvImageIdLabel.configure(activeforeground="black")
        self.RmvImageIdLabel.configure(background="#d9d9d9")
        self.RmvImageIdLabel.configure(disabledforeground="#a3a3a3")
        self.RmvImageIdLabel.configure(foreground="#000000")
        self.RmvImageIdLabel.configure(highlightbackground="#d9d9d9")
        self.RmvImageIdLabel.configure(highlightcolor="black")
        self.RmvImageIdLabel.configure(text='''Choose ID Image to Remove:''')

        self.RmvImgIDBox = ttk.Combobox(self.AdminOptions)
        self.RmvImgIDBox.place(relx=0.375, rely=0.45, relheight=0.039
                , relwidth=0.29)
        self.RmvImgIDBox.configure(textvariable=set_Tk_var)
        self.RmvImgIDBox.configure(takefocus="")

        self.ChoosenImgRmvBtn = tk.Button(self.AdminOptions)
        self.ChoosenImgRmvBtn.place(relx=0.7, rely=0.45, height=32, width=118)
        self.ChoosenImgRmvBtn.configure(activebackground="#ececec")
        self.ChoosenImgRmvBtn.configure(activeforeground="#000000")
        self.ChoosenImgRmvBtn.configure(background="#d9d9d9")
        self.ChoosenImgRmvBtn.configure(disabledforeground="#a3a3a3")
        self.ChoosenImgRmvBtn.configure(foreground="#000000")
        self.ChoosenImgRmvBtn.configure(highlightbackground="#d9d9d9")
        self.ChoosenImgRmvBtn.configure(highlightcolor="black")
        self.ChoosenImgRmvBtn.configure(pady="0")
        self.ChoosenImgRmvBtn.configure(text='''Remove''')

        self.TSeparator1_2 = ttk.Separator(self.AdminOptions)
        self.TSeparator1_2.place(relx=-0.013, rely=0.5, relwidth=1.438)

        self.AddRmvPhrasesLab = tk.Label(self.AdminOptions)
        self.AddRmvPhrasesLab.place(relx=0.038, rely=0.506, height=51, width=257)

        self.AddRmvPhrasesLab.configure(activebackground="#f9f9f9")
        self.AddRmvPhrasesLab.configure(activeforeground="black")
        self.AddRmvPhrasesLab.configure(background="#d9d9d9")
        self.AddRmvPhrasesLab.configure(disabledforeground="#a3a3a3")
        self.AddRmvPhrasesLab.configure(font="-family {Segoe UI} -size 11")
        self.AddRmvPhrasesLab.configure(foreground="#000000")
        self.AddRmvPhrasesLab.configure(highlightbackground="#d9d9d9")
        self.AddRmvPhrasesLab.configure(highlightcolor="black")
        self.AddRmvPhrasesLab.configure(text='''Add or Remove Phrases:''')

        self.ChooseImageAddLab_4 = tk.Label(self.AdminOptions)
        self.ChooseImageAddLab_4.place(relx=0.038, rely=0.575, height=31
                , width=183)
        self.ChooseImageAddLab_4.configure(activebackground="#f9f9f9")
        self.ChooseImageAddLab_4.configure(activeforeground="black")
        self.ChooseImageAddLab_4.configure(background="#d9d9d9")
        self.ChooseImageAddLab_4.configure(disabledforeground="#a3a3a3")
        self.ChooseImageAddLab_4.configure(foreground="#000000")
        self.ChooseImageAddLab_4.configure(highlightbackground="#d9d9d9")
        self.ChooseImageAddLab_4.configure(highlightcolor="black")
        self.ChooseImageAddLab_4.configure(text='''Add/Write Phrase:''')

        self.ImageIDLabel = tk.Label(self.AdminOptions)
        self.ImageIDLabel.place(relx=0.038, rely=0.394, height=31, width=127)
        self.ImageIDLabel.configure(activebackground="#f9f9f9")
        self.ImageIDLabel.configure(activeforeground="black")
        self.ImageIDLabel.configure(background="#d9d9d9")
        self.ImageIDLabel.configure(disabledforeground="#a3a3a3")
        self.ImageIDLabel.configure(foreground="#000000")
        self.ImageIDLabel.configure(highlightbackground="#d9d9d9")
        self.ImageIDLabel.configure(highlightcolor="black")
        self.ImageIDLabel.configure(text='''Image ID:''')

        self.WriteImgID = tk.Entry(self.AdminOptions)
        self.WriteImgID.place(relx=0.188, rely=0.4,height=26, relwidth=0.305)
        self.WriteImgID.configure(background="white")
        self.WriteImgID.configure(disabledforeground="#a3a3a3")
        self.WriteImgID.configure(font="TkFixedFont")
        self.WriteImgID.configure(foreground="#000000")
        self.WriteImgID.configure(highlightbackground="#d9d9d9")
        self.WriteImgID.configure(highlightcolor="black")
        self.WriteImgID.configure(insertbackground="black")
        self.WriteImgID.configure(selectbackground="#c4c4c4")
        self.WriteImgID.configure(selectforeground="black")

        self.AddImgBtn = tk.Button(self.AdminOptions)
        self.AddImgBtn.place(relx=0.525, rely=0.394, height=32, width=118)
        self.AddImgBtn.configure(activebackground="#ececec")
        self.AddImgBtn.configure(activeforeground="#000000")
        self.AddImgBtn.configure(background="#d9d9d9")
        self.AddImgBtn.configure(disabledforeground="#a3a3a3")
        self.AddImgBtn.configure(foreground="#000000")
        self.AddImgBtn.configure(highlightbackground="#d9d9d9")
        self.AddImgBtn.configure(highlightcolor="black")
        self.AddImgBtn.configure(pady="0")
        self.AddImgBtn.configure(text='''Add Image''')

        self.EntryForWritePhrase = tk.Entry(self.AdminOptions)
        self.EntryForWritePhrase.place(relx=0.263, rely=0.581, height=26
                , relwidth=0.568)
        self.EntryForWritePhrase.configure(background="white")
        self.EntryForWritePhrase.configure(disabledforeground="#a3a3a3")
        self.EntryForWritePhrase.configure(font="TkFixedFont")
        self.EntryForWritePhrase.configure(foreground="#000000")
        self.EntryForWritePhrase.configure(highlightbackground="#d9d9d9")
        self.EntryForWritePhrase.configure(highlightcolor="black")
        self.EntryForWritePhrase.configure(insertbackground="black")
        self.EntryForWritePhrase.configure(selectbackground="#c4c4c4")
        self.EntryForWritePhrase.configure(selectforeground="black")

        self.AddPhraseBtn = tk.Button(self.AdminOptions)
        self.AddPhraseBtn.place(relx=0.838, rely=0.575, height=32, width=118)
        self.AddPhraseBtn.configure(activebackground="#ececec")
        self.AddPhraseBtn.configure(activeforeground="#000000")
        self.AddPhraseBtn.configure(background="#d9d9d9")
        self.AddPhraseBtn.configure(disabledforeground="#a3a3a3")
        self.AddPhraseBtn.configure(foreground="#000000")
        self.AddPhraseBtn.configure(highlightbackground="#d9d9d9")
        self.AddPhraseBtn.configure(highlightcolor="black")
        self.AddPhraseBtn.configure(pady="0")
        self.AddPhraseBtn.configure(text='''Add Phrase''')

        self.RmvPhraseLabel = tk.Label(self.AdminOptions)
        self.RmvPhraseLabel.place(relx=0.038, rely=0.625, height=31, width=240)
        self.RmvPhraseLabel.configure(activebackground="#f9f9f9")
        self.RmvPhraseLabel.configure(activeforeground="black")
        self.RmvPhraseLabel.configure(background="#d9d9d9")
        self.RmvPhraseLabel.configure(disabledforeground="#a3a3a3")
        self.RmvPhraseLabel.configure(foreground="#000000")
        self.RmvPhraseLabel.configure(highlightbackground="#d9d9d9")
        self.RmvPhraseLabel.configure(highlightcolor="black")
        self.RmvPhraseLabel.configure(text='''Choose Phrase to remove:''')

        self.RmvPhraseBox = ttk.Combobox(self.AdminOptions)
        self.RmvPhraseBox.place(relx=0.338, rely=0.625, relheight=0.039
                , relwidth=0.29)
        self.RmvPhraseBox.configure(textvariable=set_Tk_var)
        self.RmvPhraseBox.configure(takefocus="")

        self.RmvPhraseBtn = tk.Button(self.AdminOptions)
        self.RmvPhraseBtn.place(relx=0.675, rely=0.625, height=32, width=138)
        self.RmvPhraseBtn.configure(activebackground="#ececec")
        self.RmvPhraseBtn.configure(activeforeground="#000000")
        self.RmvPhraseBtn.configure(background="#d9d9d9")
        self.RmvPhraseBtn.configure(disabledforeground="#a3a3a3")
        self.RmvPhraseBtn.configure(foreground="#000000")
        self.RmvPhraseBtn.configure(highlightbackground="#d9d9d9")
        self.RmvPhraseBtn.configure(highlightcolor="black")
        self.RmvPhraseBtn.configure(pady="0")
        self.RmvPhraseBtn.configure(text='''Remove Phrase''')

        self.TSeparator1_3 = ttk.Separator(self.AdminOptions)
        self.TSeparator1_3.place(relx=-0.013, rely=0.688, relwidth=1.438)

        self.SndMsgToMentors = tk.Label(self.AdminOptions)
        self.SndMsgToMentors.place(relx=0.05, rely=0.725, height=31, width=226)
        self.SndMsgToMentors.configure(background="#d9d9d9")
        self.SndMsgToMentors.configure(disabledforeground="#a3a3a3")
        self.SndMsgToMentors.configure(foreground="#000000")
        self.SndMsgToMentors.configure(text='''Send Messages to Mentors:''')

        self.EntryMsgToMentors = tk.Entry(self.AdminOptions)
        self.EntryMsgToMentors.place(relx=0.363, rely=0.7, height=76
                , relwidth=0.38)
        self.EntryMsgToMentors.configure(background="white")
        self.EntryMsgToMentors.configure(disabledforeground="#a3a3a3")
        self.EntryMsgToMentors.configure(font="TkFixedFont")
        self.EntryMsgToMentors.configure(foreground="#000000")
        self.EntryMsgToMentors.configure(insertbackground="black")
        self.EntryMsgToMentors.configure(width=304)

        self.SendMsgBtn = tk.Button(self.AdminOptions)
        self.SendMsgBtn.place(relx=0.794, rely=0.725, height=32, width=118)
        self.SendMsgBtn.configure(activebackground="#ececec")
        self.SendMsgBtn.configure(activeforeground="#000000")
        self.SendMsgBtn.configure(background="#d9d9d9")
        self.SendMsgBtn.configure(disabledforeground="#a3a3a3")
        self.SendMsgBtn.configure(foreground="#000000")
        self.SendMsgBtn.configure(highlightbackground="#d9d9d9")
        self.SendMsgBtn.configure(highlightcolor="black")
        self.SendMsgBtn.configure(pady="0")
        self.SendMsgBtn.configure(text='''Send''')

        self.TSeparator1_2 = ttk.Separator(self.AdminOptions)
        self.TSeparator1_2.place(relx=-0.025, rely=0.813, relwidth=1.438)

        self.AddRmvPhrasesLab_3 = tk.Label(self.AdminOptions)
        self.AddRmvPhrasesLab_3.place(relx=0.044, rely=0.825, height=51
                , width=257)
        self.AddRmvPhrasesLab_3.configure(activebackground="#f9f9f9")
        self.AddRmvPhrasesLab_3.configure(activeforeground="black")
        self.AddRmvPhrasesLab_3.configure(background="#d9d9d9")
        self.AddRmvPhrasesLab_3.configure(disabledforeground="#a3a3a3")
        self.AddRmvPhrasesLab_3.configure(font="-family {Segoe UI} -size 11")
        self.AddRmvPhrasesLab_3.configure(foreground="#000000")
        self.AddRmvPhrasesLab_3.configure(highlightbackground="#d9d9d9")
        self.AddRmvPhrasesLab_3.configure(highlightcolor="black")
        self.AddRmvPhrasesLab_3.configure(text='''Statistics and security logs:''')

        self.PswMisBtn = tk.Button(self.AdminOptions)
        self.PswMisBtn.place(relx=0.044, rely=0.888, height=72, width=128)
        self.PswMisBtn.configure(activebackground="#ececec")
        self.PswMisBtn.configure(activeforeground="#000000")
        self.PswMisBtn.configure(background="#d9d9d9")
        self.PswMisBtn.configure(disabledforeground="#a3a3a3")
        self.PswMisBtn.configure(foreground="#000000")
        self.PswMisBtn.configure(highlightbackground="#d9d9d9")
        self.PswMisBtn.configure(highlightcolor="black")
        self.PswMisBtn.configure(pady="0")
        self.PswMisBtn.configure(text='''Invalid login 
report''')
        self.PswMisBtn.configure(width=128)

        self.OnlineUsersBtn = tk.Button(self.AdminOptions)
        self.OnlineUsersBtn.place(relx=0.238, rely=0.888, height=72, width=128)
        self.OnlineUsersBtn.configure(activebackground="#ececec")
        self.OnlineUsersBtn.configure(activeforeground="#000000")
        self.OnlineUsersBtn.configure(background="#d9d9d9")
        self.OnlineUsersBtn.configure(disabledforeground="#a3a3a3")
        self.OnlineUsersBtn.configure(foreground="#000000")
        self.OnlineUsersBtn.configure(highlightbackground="#d9d9d9")
        self.OnlineUsersBtn.configure(highlightcolor="black")
        self.OnlineUsersBtn.configure(pady="0")
        self.OnlineUsersBtn.configure(text='''Online Users''')
        self.OnlineUsersBtn.configure(width=128)

        self.ExceptionLogBtn = tk.Button(self.AdminOptions)
        self.ExceptionLogBtn.place(relx=0.431, rely=0.888, height=72, width=128)
        self.ExceptionLogBtn.configure(activebackground="#ececec")
        self.ExceptionLogBtn.configure(activeforeground="#000000")
        self.ExceptionLogBtn.configure(background="#d9d9d9")
        self.ExceptionLogBtn.configure(disabledforeground="#a3a3a3")
        self.ExceptionLogBtn.configure(foreground="#000000")
        self.ExceptionLogBtn.configure(highlightbackground="#d9d9d9")
        self.ExceptionLogBtn.configure(highlightcolor="black")
        self.ExceptionLogBtn.configure(pady="0")
        self.ExceptionLogBtn.configure(text='''Exceptions Log''')
        self.ExceptionLogBtn.configure(width=128)

        self.FeedBackLogBtn = tk.Button(self.AdminOptions)
        self.FeedBackLogBtn.place(relx=0.625, rely=0.888, height=72, width=128)
        self.FeedBackLogBtn.configure(activebackground="#ececec")
        self.FeedBackLogBtn.configure(activeforeground="#000000")
        self.FeedBackLogBtn.configure(background="#d9d9d9")
        self.FeedBackLogBtn.configure(disabledforeground="#a3a3a3")
        self.FeedBackLogBtn.configure(foreground="#000000")
        self.FeedBackLogBtn.configure(highlightbackground="#d9d9d9")
        self.FeedBackLogBtn.configure(highlightcolor="black")
        self.FeedBackLogBtn.configure(pady="0")
        self.FeedBackLogBtn.configure(text='''Feed Back Log''')
        self.FeedBackLogBtn.configure(width=128)

        self.StatisticLogBtn = tk.Button(self.AdminOptions)
        self.StatisticLogBtn.place(relx=0.813, rely=0.888, height=72, width=128)
        self.StatisticLogBtn.configure(activebackground="#ececec")
        self.StatisticLogBtn.configure(activeforeground="#000000")
        self.StatisticLogBtn.configure(background="#d9d9d9")
        self.StatisticLogBtn.configure(disabledforeground="#a3a3a3")
        self.StatisticLogBtn.configure(foreground="#000000")
        self.StatisticLogBtn.configure(highlightbackground="#d9d9d9")
        self.StatisticLogBtn.configure(highlightcolor="black")
        self.StatisticLogBtn.configure(pady="0")
        self.StatisticLogBtn.configure(text='''Statistic Log''')
        self.StatisticLogBtn.configure(width=128)

        self.ChooseUserIDBox = ttk.Combobox(self.AdminOptions)
        self.ChooseUserIDBox.place(relx=0.225, rely=0.15, relheight=0.039
                , relwidth=0.29)
        self.ChooseUserIDBox.configure(textvariable=set_Tk_var)
        self.ChooseUserIDBox.configure(takefocus="")

        self.ChangePassLabel = tk.Label(self.AdminOptions)
        self.ChangePassLabel.place(relx=0.031, rely=0.213, height=31, width=297)
        self.ChangePassLabel.configure(activebackground="#f9f9f9")
        self.ChangePassLabel.configure(activeforeground="black")
        self.ChangePassLabel.configure(background="#d9d9d9")
        self.ChangePassLabel.configure(disabledforeground="#a3a3a3")
        self.ChangePassLabel.configure(foreground="#000000")
        self.ChangePassLabel.configure(highlightbackground="#d9d9d9")
        self.ChangePassLabel.configure(highlightcolor="black")
        self.ChangePassLabel.configure(text='''Change Passwod to Choosen User:''')
        self.ChangePassLabel.configure(width=297)

        self.EntryChangePass = tk.Entry(self.AdminOptions)
        self.EntryChangePass.place(relx=0.413, rely=0.213, height=26
                , relwidth=0.305)
        self.EntryChangePass.configure(background="white")
        self.EntryChangePass.configure(disabledforeground="#a3a3a3")
        self.EntryChangePass.configure(font="TkFixedFont")
        self.EntryChangePass.configure(foreground="#000000")
        self.EntryChangePass.configure(insertbackground="black")

        self.UpdatePassBtn = tk.Button(self.AdminOptions)
        self.UpdatePassBtn.place(relx=0.756, rely=0.213, height=32, width=148)
        self.UpdatePassBtn.configure(activebackground="#ececec")
        self.UpdatePassBtn.configure(activeforeground="#000000")
        self.UpdatePassBtn.configure(background="#d9d9d9")
        self.UpdatePassBtn.configure(disabledforeground="#a3a3a3")
        self.UpdatePassBtn.configure(foreground="#000000")
        self.UpdatePassBtn.configure(highlightbackground="#d9d9d9")
        self.UpdatePassBtn.configure(highlightcolor="black")
        self.UpdatePassBtn.configure(pady="0")
        self.UpdatePassBtn.configure(text='''Update Password''')
        self.UpdatePassBtn.configure(width=148)

        action_with_args = partial(LogicGui.LogicGui.LogoutfromAdmin, self, top)

        self.AdminLogOutBtn = tk.Button(self.AdminOptions,command=action_with_args)
        self.AdminLogOutBtn.place(relx=0.863, rely=0.013, height=52, width=98)
        self.AdminLogOutBtn.configure(activebackground="#ececec")
        self.AdminLogOutBtn.configure(activeforeground="#000000")
        self.AdminLogOutBtn.configure(background="#d9d9d9")
        self.AdminLogOutBtn.configure(disabledforeground="#a3a3a3")
        self.AdminLogOutBtn.configure(foreground="#000000")
        self.AdminLogOutBtn.configure(highlightbackground="#d9d9d9")
        self.AdminLogOutBtn.configure(highlightcolor="black")
        self.AdminLogOutBtn.configure(pady="0")
        self.AdminLogOutBtn.configure(text='''LogOut''')
        self.AdminLogOutBtn.configure(width=98)






