#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 4.21
#  in conjunction with Tcl version 8.6
#    Mar 08, 2019 04:23:31 AM +0200  platform: Windows NT

import sys

try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True
    
import LogicGui
from functools import partial
import sendMsgs

w = None
def create_FeedBackFrame(root, *args, **kwargs):
    '''Starting point when module is imported by another program.'''
    global w, w_win, rt
    rt = root
    w = tk.Toplevel (root)
    top = FeedBackFrame (w)
    init(w, top, *args, **kwargs)
    return (w, top)

def init(top, gui, *args, **kwargs):
    global w, top_level, root
    w = gui
    top_level = top
    root = top

def destroy_FeedBackFrame():
    global w
    w.destroy()
    w = None

class FeedBackFrame:
    def create_FeedBackWin(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85'
        _ana2color = '#ececec' # Closest X11 color: 'gray92'
        font9 = "-family {Segoe UI} -size 20 -weight bold"

        top.geometry("1050x802+530+101")
        top.title("New Toplevel")
        top.configure(background="#d9d9d9")

        self.feedBackDict = {}

        self.Feedback = tk.Frame(top)
        self.Feedback.place(relx=0.124, rely=0.137, relheight=0.748
                , relwidth=0.762)
        self.Feedback.configure(relief='groove')
        self.Feedback.configure(borderwidth="2")
        self.Feedback.configure(relief='groove')
        self.Feedback.configure(background="#d9d9d9")
        self.Feedback.configure(width=125)

        self.FeedbackLabel = tk.Label(self.Feedback)
        self.FeedbackLabel.place(relx=0.375, rely=0.05, height=116, width=181)
        self.FeedbackLabel.configure(background="#d9d9d9")
        self.FeedbackLabel.configure(disabledforeground="#a3a3a3")
        self.FeedbackLabel.configure(font=font9)
        self.FeedbackLabel.configure(foreground="#000000")
        self.FeedbackLabel.configure(text='''Feedback''')
        self.FeedbackLabel.configure(width=181)

        self.FeedbackText = tk.Entry(self.Feedback)
        self.FeedbackText.place(relx=0.25, rely=0.267, height=204, relwidth=0.48)

        self.FeedbackText.configure(background="white")
        self.FeedbackText.configure(disabledforeground="#a3a3a3")
        self.FeedbackText.configure(font="TkFixedFont")
        self.FeedbackText.configure(foreground="#000000")
        self.FeedbackText.configure(insertbackground="black")
        self.FeedbackText.configure(width=384)
        
        action_with_args = partial(LogicGui.LogicGui.BackToInfoHelp,self,top)

        self.Feedbackback = tk.Button(self.Feedback, command = action_with_args)
        self.Feedbackback.place(relx=0.138, rely=0.767, height=83, width=196)
        self.Feedbackback.configure(activebackground="#ececec")
        self.Feedbackback.configure(activeforeground="#000000")
        self.Feedbackback.configure(background="#d9d9d9")
        self.Feedbackback.configure(disabledforeground="#a3a3a3")
        self.Feedbackback.configure(foreground="#000000")
        self.Feedbackback.configure(highlightbackground="#d9d9d9")
        self.Feedbackback.configure(highlightcolor="black")
        self.Feedbackback.configure(pady="0")
        self.Feedbackback.configure(text='''Back''')
        self.Feedbackback.configure(width=196)

        action_with_args = partial(sendMsgs.globalFeedBack,self.feedBackDict)

        self.SendFeedback = tk.Button(self.Feedback, command=action_with_args)
        self.SendFeedback.place(relx=0.588, rely=0.767, height=83, width=206)
        self.SendFeedback.configure(activebackground="#ececec")
        self.SendFeedback.configure(activeforeground="#000000")
        self.SendFeedback.configure(background="#d9d9d9")
        self.SendFeedback.configure(disabledforeground="#a3a3a3")
        self.SendFeedback.configure(foreground="#000000")
        self.SendFeedback.configure(highlightbackground="#d9d9d9")
        self.SendFeedback.configure(highlightcolor="black")
        self.SendFeedback.configure(pady="0")
        self.SendFeedback.configure(text='''Send''')
        self.SendFeedback.configure(width=206)


        self.feedBackDict["FeedbackText"] = self.FeedbackText




