#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 4.21
#  in conjunction with Tcl version 8.6
#    Mar 09, 2019 05:47:20 AM +0200  platform: Windows NT

import sys
from functools import partial
import GUI
import LogicGui
import GUIandDBCommunication


try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True



w = None
def create_UserRegister(root, *args, **kwargs):
    '''Starting point when module is imported by another program.'''
    global w, w_win, rt
    rt = root
    w = tk.Toplevel (root)
    top = UserRegister (w)
    init(w, top, *args, **kwargs)
    return (w, top)

def init(top, gui, *args, **kwargs):
    global w, top_level, root
    w = gui
    top_level = top
    root = top

def destroy_UserRegister():
    global w
    w.destroy()
    w = None
    
class UserRegister:
    def Create_RegNewUSer(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85'
        _ana2color = '#ececec' # Closest X11 color: 'gray92'
        font9 = "-family {Segoe UI} -size 12"
        
        self.UserInput={}
        
        top.geometry("1174x912+371+35")
        top.title("New Toplevel")
        top.configure(background="#d9d9d9")
        top.configure(highlightbackground="#d9d9d9")
        top.configure(highlightcolor="black")
        

        self.PatientRegisterFrame = tk.Frame(top)
        self.PatientRegisterFrame.place(relx=0.145, rely=0.066, relheight=0.877 , relwidth=0.681)

        self.PatientRegisterFrame.configure(relief='groove')
        self.PatientRegisterFrame.configure(borderwidth="2")
        self.PatientRegisterFrame.configure(relief='groove')
        self.PatientRegisterFrame.configure(background="#d9d9d9")
        self.PatientRegisterFrame.configure(highlightbackground="#d9d9d9")
        self.PatientRegisterFrame.configure(highlightcolor="black")
        self.PatientRegisterFrame.configure(width=800)

        self.PatientRegisterLabel = tk.Label(self.PatientRegisterFrame)
        self.PatientRegisterLabel.place(relx=0.288, rely=0.013, height=56 , relwidth=0.681)
        self.PatientRegisterLabel.configure(activebackground="#f9f9f9")
        self.PatientRegisterLabel.configure(activeforeground="black")
        self.PatientRegisterLabel.configure(background="#d9d9d9")
        self.PatientRegisterLabel.configure(disabledforeground="#a3a3a3")
        self.PatientRegisterLabel.configure(font="-family {Segoe UI} -size 20 -weight bold -underline 1")
        self.PatientRegisterLabel.configure(foreground="#000000")
        self.PatientRegisterLabel.configure(highlightbackground="#d9d9d9")
        self.PatientRegisterLabel.configure(highlightcolor="black")
        self.PatientRegisterLabel.configure(text='''New User Register''')





        ######lable########
        self.MentorIDLabel = tk.Label(self.PatientRegisterFrame)
        self.MentorIDLabel.place(relx=0.038, rely=0.1, height=36, width=116)
        self.MentorIDLabel.configure(activebackground="#f9f9f9")
        self.MentorIDLabel.configure(activeforeground="black")
        self.MentorIDLabel.configure(background="#d9d9d9")
        self.MentorIDLabel.configure(disabledforeground="#a3a3a3")
        self.MentorIDLabel.configure(font="-family {Segoe UI} -size 12")
        self.MentorIDLabel.configure(foreground="#000000")
        self.MentorIDLabel.configure(highlightbackground="#d9d9d9")
        self.MentorIDLabel.configure(highlightcolor="black")
        self.MentorIDLabel.configure(text='''Mentor ID:''')

        self.MentorID = tk.Entry(self.PatientRegisterFrame)
        self.MentorID.place(relx=0.213, rely=0.113,height=24, relwidth=0.255)
        self.MentorID.configure(background="white")
        self.MentorID.configure(disabledforeground="#a3a3a3")
        self.MentorID.configure(font="TkFixedFont")
        self.MentorID.configure(foreground="#000000")
        self.MentorID.configure(highlightbackground="#d9d9d9")
        self.MentorID.configure(highlightcolor="black")
        self.MentorID.configure(insertbackground="black")
        self.MentorID.configure(selectbackground="#c4c4c4")
        self.MentorID.configure(selectforeground="black")
        



        self.PatientNameLabel = tk.Label(self.PatientRegisterFrame)
        self.PatientNameLabel.place(relx=0.025, rely=0.15, height=34, width=102)
        self.PatientNameLabel.configure(activebackground="#f9f9f9")
        self.PatientNameLabel.configure(activeforeground="black")
        self.PatientNameLabel.configure(background="#d9d9d9")
        self.PatientNameLabel.configure(disabledforeground="#a3a3a3")
        self.PatientNameLabel.configure(font="-family {Segoe UI} -size 12")
        self.PatientNameLabel.configure(foreground="#000000")
        self.PatientNameLabel.configure(highlightbackground="#d9d9d9")
        self.PatientNameLabel.configure(highlightcolor="black")
        self.PatientNameLabel.configure(text='''Name:''')

        self.PatientLastNameLabel = tk.Label(self.PatientRegisterFrame)
        self.PatientLastNameLabel.place(relx=0.5, rely=0.15, height=34 , width=101)
        self.PatientLastNameLabel.configure(activebackground="#f9f9f9")
        self.PatientLastNameLabel.configure(activeforeground="black")
        self.PatientLastNameLabel.configure(background="#d9d9d9")
        self.PatientLastNameLabel.configure(disabledforeground="#a3a3a3")
        self.PatientLastNameLabel.configure(font="-family {Segoe UI} -size 12")
        self.PatientLastNameLabel.configure(foreground="#000000")
        self.PatientLastNameLabel.configure(highlightbackground="#d9d9d9")
        self.PatientLastNameLabel.configure(highlightcolor="black")
        self.PatientLastNameLabel.configure(text='''Last Name:''')

        self.PatientGenderLabel = tk.Label(self.PatientRegisterFrame)
        self.PatientGenderLabel.place(relx=0.025, rely=0.275, height=44, width=112)
        self.PatientGenderLabel.configure(activebackground="#f9f9f9")
        self.PatientGenderLabel.configure(activeforeground="black")
        self.PatientGenderLabel.configure(background="#d9d9d9")
        self.PatientGenderLabel.configure(disabledforeground="#a3a3a3")
        self.PatientGenderLabel.configure(font="-family {Segoe UI} -size 12")
        self.PatientGenderLabel.configure(foreground="#000000")
        self.PatientGenderLabel.configure(highlightbackground="#d9d9d9")
        self.PatientGenderLabel.configure(highlightcolor="black")
        self.PatientGenderLabel.configure(text='''Gender:''')

        self.PatientBirthdayLabel = tk.Label(self.PatientRegisterFrame)
        self.PatientBirthdayLabel.place(relx=0.05, rely=0.213, height=34 , width=121)
        self.PatientBirthdayLabel.configure(activebackground="#f9f9f9")
        self.PatientBirthdayLabel.configure(activeforeground="black")
        self.PatientBirthdayLabel.configure(background="#d9d9d9")
        self.PatientBirthdayLabel.configure(disabledforeground="#a3a3a3")
        self.PatientBirthdayLabel.configure(font="-family {Segoe UI} -size 12")
        self.PatientBirthdayLabel.configure(foreground="#000000")
        self.PatientBirthdayLabel.configure(highlightbackground="#d9d9d9")
        self.PatientBirthdayLabel.configure(highlightcolor="black")
        self.PatientBirthdayLabel.configure(text='''Date of birth:''')

        self.Patientcontact1label = tk.Label(self.PatientRegisterFrame)
        self.Patientcontact1label.place(relx=0.05, rely=0.35, height=34, width=89)
        self.Patientcontact1label.configure(activebackground="#f9f9f9")
        self.Patientcontact1label.configure(activeforeground="black")
        self.Patientcontact1label.configure(background="#d9d9d9")
        self.Patientcontact1label.configure(disabledforeground="#a3a3a3")
        self.Patientcontact1label.configure(font="-family {Segoe UI} -size 12")
        self.Patientcontact1label.configure(foreground="#000000")
        self.Patientcontact1label.configure(highlightbackground="#d9d9d9")
        self.Patientcontact1label.configure(highlightcolor="black")
        self.Patientcontact1label.configure(text='''Contact1:''')

        self.Patientcontact2Label = tk.Label(self.PatientRegisterFrame)
        self.Patientcontact2Label.place(relx=0.5, rely=0.338, height=26 , width=88)
        self.Patientcontact2Label.configure(activebackground="#f9f9f9")
        self.Patientcontact2Label.configure(activeforeground="black")
        self.Patientcontact2Label.configure(background="#d9d9d9")
        self.Patientcontact2Label.configure(disabledforeground="#a3a3a3")
        self.Patientcontact2Label.configure(font="-family {Segoe UI} -size 12")
        self.Patientcontact2Label.configure(foreground="#000000")
        self.Patientcontact2Label.configure(highlightbackground="#d9d9d9")
        self.Patientcontact2Label.configure(highlightcolor="black")
        self.Patientcontact2Label.configure(text='''Contact2:''')

        self.PatientAdressLabel = tk.Label(self.PatientRegisterFrame)
        self.PatientAdressLabel.place(relx=0.5, rely=0.263, height=34, width=80)
        self.PatientAdressLabel.configure(activebackground="#f9f9f9")
        self.PatientAdressLabel.configure(activeforeground="black")
        self.PatientAdressLabel.configure(background="#d9d9d9")
        self.PatientAdressLabel.configure(disabledforeground="#a3a3a3")
        self.PatientAdressLabel.configure(font="-family {Segoe UI} -size 12")
        self.PatientAdressLabel.configure(foreground="#000000")
        self.PatientAdressLabel.configure(highlightbackground="#d9d9d9")
        self.PatientAdressLabel.configure(highlightcolor="black")
        self.PatientAdressLabel.configure(text='''Address:''')

        self.PatientAgeLabel = tk.Label(self.PatientRegisterFrame)
        self.PatientAgeLabel.place(relx=0.5, rely=0.2, height=34, width=45)
        self.PatientAgeLabel.configure(activebackground="#f9f9f9")
        self.PatientAgeLabel.configure(activeforeground="black")
        self.PatientAgeLabel.configure(background="#d9d9d9")
        self.PatientAgeLabel.configure(disabledforeground="#a3a3a3")
        self.PatientAgeLabel.configure(font="-family {Segoe UI} -size 12")
        self.PatientAgeLabel.configure(foreground="#000000")
        self.PatientAgeLabel.configure(highlightbackground="#d9d9d9")
        self.PatientAgeLabel.configure(highlightcolor="black")
        self.PatientAgeLabel.configure(text='''Age:''')

        self.UserIDLabel = tk.Label(self.PatientRegisterFrame)
        self.UserIDLabel.place(relx=0.463, rely=0.1, height=34, width=79)
        self.UserIDLabel.configure(activebackground="#f9f9f9")
        self.UserIDLabel.configure(activeforeground="black")
        self.UserIDLabel.configure(background="#d9d9d9")
        self.UserIDLabel.configure(disabledforeground="#a3a3a3")
        self.UserIDLabel.configure(font="-family {Segoe UI} -size 12")
        self.UserIDLabel.configure(foreground="#000000")
        self.UserIDLabel.configure(highlightbackground="#d9d9d9")
        self.UserIDLabel.configure(highlightcolor="black")
        self.UserIDLabel.configure(text='''ID:''')

        self.PetientName = tk.Entry(self.PatientRegisterFrame)
        self.PetientName.place(relx=0.213, rely=0.163, height=24, relwidth=0.255)
        self.PetientName.configure(background="white")
        self.PetientName.configure(disabledforeground="#a3a3a3")
        self.PetientName.configure(font="TkFixedFont")
        self.PetientName.configure(foreground="#000000")
        self.PetientName.configure(highlightbackground="#d9d9d9")
        self.PetientName.configure(highlightcolor="black")
        self.PetientName.configure(insertbackground="black")
        self.PetientName.configure(selectbackground="#c4c4c4")
        self.PetientName.configure(selectforeground="black")

        self.PatientDOB = tk.Entry(self.PatientRegisterFrame)
        self.PatientDOB.place(relx=0.213, rely=0.213,height=24, relwidth=0.255)
        self.PatientDOB.configure(background="white")
        self.PatientDOB.configure(disabledforeground="#a3a3a3")
        self.PatientDOB.configure(font="TkFixedFont")
        self.PatientDOB.configure(foreground="#000000")
        self.PatientDOB.configure(highlightbackground="#d9d9d9")
        self.PatientDOB.configure(highlightcolor="black")
        self.PatientDOB.configure(insertbackground="black")
        self.PatientDOB.configure(selectbackground="#c4c4c4")
        self.PatientDOB.configure(selectforeground="black")

        self.UserGender = tk.Entry(self.PatientRegisterFrame)
        self.UserGender.place(relx=0.213, rely=0.288,height=24, relwidth=0.255)
        self.UserGender.configure(background="white")
        self.UserGender.configure(disabledforeground="#a3a3a3")
        self.UserGender.configure(font="TkFixedFont")
        self.UserGender.configure(foreground="#000000")
        self.UserGender.configure(highlightbackground="#d9d9d9")
        self.UserGender.configure(highlightcolor="black")
        self.UserGender.configure(insertbackground="black")
        self.UserGender.configure(selectbackground="#c4c4c4")
        self.UserGender.configure(selectforeground="black")

        self.UserContact1 = tk.Entry(self.PatientRegisterFrame)
        self.UserContact1.place(relx=0.213, rely=0.35, height=24, relwidth=0.255)
        self.UserContact1.configure(background="white")
        self.UserContact1.configure(disabledforeground="#a3a3a3")
        self.UserContact1.configure(font="TkFixedFont")
        self.UserContact1.configure(foreground="#000000")
        self.UserContact1.configure(highlightbackground="#d9d9d9")
        self.UserContact1.configure(highlightcolor="black")
        self.UserContact1.configure(insertbackground="black")
        self.UserContact1.configure(selectbackground="#c4c4c4")
        self.UserContact1.configure(selectforeground="black")

        self.UserID = tk.Entry(self.PatientRegisterFrame)
        self.UserID.place(relx=0.688, rely=0.1,height=24, relwidth=0.255)
        self.UserID.configure(background="white")
        self.UserID.configure(disabledforeground="#a3a3a3")
        self.UserID.configure(font="TkFixedFont")
        self.UserID.configure(foreground="#000000")
        self.UserID.configure(highlightbackground="#d9d9d9")
        self.UserID.configure(highlightcolor="black")
        self.UserID.configure(insertbackground="black")
        self.UserID.configure(selectbackground="#c4c4c4")
        self.UserID.configure(selectforeground="black")

        self.UserLastName = tk.Entry(self.PatientRegisterFrame)
        self.UserLastName.place(relx=0.688, rely=0.15, height=24, relwidth=0.255)
        self.UserLastName.configure(background="white")
        self.UserLastName.configure(disabledforeground="#a3a3a3")
        self.UserLastName.configure(font="TkFixedFont")
        self.UserLastName.configure(foreground="#000000")
        self.UserLastName.configure(highlightbackground="#d9d9d9")
        self.UserLastName.configure(highlightcolor="black")
        self.UserLastName.configure(insertbackground="black")
        self.UserLastName.configure(selectbackground="#c4c4c4")
        self.UserLastName.configure(selectforeground="black")

        self.UserAge = tk.Entry(self.PatientRegisterFrame)
        self.UserAge.place(relx=0.688, rely=0.213,height=24, relwidth=0.255)
        self.UserAge.configure(background="white")
        self.UserAge.configure(disabledforeground="#a3a3a3")
        self.UserAge.configure(font="TkFixedFont")
        self.UserAge.configure(foreground="#000000")
        self.UserAge.configure(highlightbackground="#d9d9d9")
        self.UserAge.configure(highlightcolor="black")
        self.UserAge.configure(insertbackground="black")
        self.UserAge.configure(selectbackground="#c4c4c4")
        self.UserAge.configure(selectforeground="black")

        self.UserAddress = tk.Entry(self.PatientRegisterFrame)
        self.UserAddress.place(relx=0.688, rely=0.275, height=24, relwidth=0.255)
        self.UserAddress.configure(background="white")
        self.UserAddress.configure(disabledforeground="#a3a3a3")
        self.UserAddress.configure(font="TkFixedFont")
        self.UserAddress.configure(foreground="#000000")
        self.UserAddress.configure(highlightbackground="#d9d9d9")
        self.UserAddress.configure(highlightcolor="black")
        self.UserAddress.configure(insertbackground="black")
        self.UserAddress.configure(selectbackground="#c4c4c4")
        self.UserAddress.configure(selectforeground="black")

        self.UserContact2 = tk.Entry(self.PatientRegisterFrame)
        self.UserContact2.place(relx=0.688, rely=0.338, height=24 , relwidth=0.255)
        self.UserContact2.configure(background="white")
        self.UserContact2.configure(disabledforeground="#a3a3a3")
        self.UserContact2.configure(font="TkFixedFont")
        self.UserContact2.configure(foreground="#000000")
        self.UserContact2.configure(highlightbackground="#d9d9d9")
        self.UserContact2.configure(highlightcolor="black")
        self.UserContact2.configure(insertbackground="black")
        self.UserContact2.configure(selectbackground="#c4c4c4")
        self.UserContact2.configure(selectforeground="black")






        self.UserMedical = tk.Entry(self.PatientRegisterFrame)
        self.UserMedical.place(relx=0.025, rely=0.763, height=154, relwidth=0.255)
        self.UserMedical.configure(background="white")
        self.UserMedical.configure(disabledforeground="#a3a3a3")
        self.UserMedical.configure(font="TkFixedFont")
        self.UserMedical.configure(foreground="#000000")
        self.UserMedical.configure(highlightbackground="#d9d9d9")
        self.UserMedical.configure(highlightcolor="black")
        self.UserMedical.configure(insertbackground="black")
        self.UserMedical.configure(selectbackground="#c4c4c4")
        self.UserMedical.configure(selectforeground="black")

        self.UserDiet = tk.Entry(self.PatientRegisterFrame)
        self.UserDiet.place(relx=0.688, rely=0.75,height=154, relwidth=0.255)
        self.UserDiet.configure(background="white")
        self.UserDiet.configure(disabledforeground="#a3a3a3")
        self.UserDiet.configure(font="TkFixedFont")
        self.UserDiet.configure(foreground="#000000")
        self.UserDiet.configure(highlightbackground="#d9d9d9")
        self.UserDiet.configure(highlightcolor="black")
        self.UserDiet.configure(insertbackground="black")
        self.UserDiet.configure(selectbackground="#c4c4c4")
        self.UserDiet.configure(selectforeground="black")





        self.UserMedicalLabel = tk.Label(self.PatientRegisterFrame)
        self.UserMedicalLabel.place(relx=0.038, rely=0.7, height=26, width=122)
        self.UserMedicalLabel.configure(activebackground="#f9f9f9")
        self.UserMedicalLabel.configure(activeforeground="black")
        self.UserMedicalLabel.configure(background="#d9d9d9")
        self.UserMedicalLabel.configure(disabledforeground="#a3a3a3")
        self.UserMedicalLabel.configure(font="-family {Segoe UI} -size 12")
        self.UserMedicalLabel.configure(foreground="#000000")
        self.UserMedicalLabel.configure(highlightbackground="#d9d9d9")
        self.UserMedicalLabel.configure(highlightcolor="black")
        self.UserMedicalLabel.configure(text='''Medical info:''')
        self.UserMedicalLabel.configure(text='''Medical info:''')

        self.UserDietLabel = tk.Label(self.PatientRegisterFrame,)
        self.UserDietLabel.place(relx=0.7, rely=0.7, height=34, width=46)
        self.UserDietLabel.configure(activebackground="#f9f9f9")
        self.UserDietLabel.configure(activeforeground="black")
        self.UserDietLabel.configure(background="#d9d9d9")
        self.UserDietLabel.configure(disabledforeground="#a3a3a3")
        self.UserDietLabel.configure(font="-family {Segoe UI} -size 12")
        self.UserDietLabel.configure(foreground="#000000")
        self.UserDietLabel.configure(highlightbackground="#d9d9d9")
        self.UserDietLabel.configure(highlightcolor="black")
        self.UserDietLabel.configure(text='''Diet:''')




        self.UserPhone = tk.Entry(self.PatientRegisterFrame)
        self.UserPhone.place(relx=0.213, rely=0.413,height=24, relwidth=0.255)
        self.UserPhone.configure(background="white")
        self.UserPhone.configure(disabledforeground="#a3a3a3")
        self.UserPhone.configure(font="TkFixedFont")
        self.UserPhone.configure(foreground="#000000")
        self.UserPhone.configure(highlightbackground="#d9d9d9")
        self.UserPhone.configure(highlightcolor="black")
        self.UserPhone.configure(insertbackground="black")
        self.UserPhone.configure(selectbackground="#c4c4c4")
        self.UserPhone.configure(selectforeground="black")

        self.UserPhoneLabel = tk.Label(self.PatientRegisterFrame)
        self.UserPhoneLabel.place(relx=0.025, rely=0.4, height=34, width=105)
        self.UserPhoneLabel.configure(activebackground="#f9f9f9")
        self.UserPhoneLabel.configure(activeforeground="black")
        self.UserPhoneLabel.configure(background="#d9d9d9")
        self.UserPhoneLabel.configure(disabledforeground="#a3a3a3")
        self.UserPhoneLabel.configure(font="-family {Segoe UI} -size 12")
        self.UserPhoneLabel.configure(foreground="#000000")
        self.UserPhoneLabel.configure(highlightbackground="#d9d9d9")
        self.UserPhoneLabel.configure(highlightcolor="black")
        self.UserPhoneLabel.configure(text='''Phone:''')



        action_with_args = partial(GUIandDBCommunication.GUIandDB.checkUserInput, self, self.UserInput, top)

        self.RegisterNewUser = tk.Button(self.PatientRegisterFrame,command = action_with_args)
        self.RegisterNewUser.place(relx=0.375, rely=0.725, height=73, width=176)
        self.RegisterNewUser.configure(activebackground="#ececec")
        self.RegisterNewUser.configure(activeforeground="#000000")
        self.RegisterNewUser.configure(background="#d9d9d9")
        self.RegisterNewUser.configure(disabledforeground="#a3a3a3")
        self.RegisterNewUser.configure(foreground="#000000")
        self.RegisterNewUser.configure(highlightbackground="#d9d9d9")
        self.RegisterNewUser.configure(highlightcolor="black")
        self.RegisterNewUser.configure(pady="0")
        self.RegisterNewUser.configure(text='''Register''')
        
        action_with_args = partial(LogicGui.LogicGui.returnToMainFromUser,self, top)
        
        self.NewUserRegisterBack = tk.Button(self.PatientRegisterFrame, command=action_with_args)
        self.NewUserRegisterBack.place(relx=0.4, rely=0.875, height=63 , width=146)
        self.NewUserRegisterBack.configure(activebackground="#ececec")
        self.NewUserRegisterBack.configure(activeforeground="#000000")
        self.NewUserRegisterBack.configure(background="#d9d9d9")
        self.NewUserRegisterBack.configure(disabledforeground="#a3a3a3")
        self.NewUserRegisterBack.configure(foreground="#000000")
        self.NewUserRegisterBack.configure(highlightbackground="#d9d9d9")
        self.NewUserRegisterBack.configure(highlightcolor="black")
        self.NewUserRegisterBack.configure(pady="0")
        self.NewUserRegisterBack.configure(text='''Back''')

        self.UserPassword1 = tk.Entry(self.PatientRegisterFrame)
        self.UserPassword1.place(relx=0.2, rely=0.538, height=24, relwidth=0.255)
        self.UserPassword1.configure(background="white")
        self.UserPassword1.configure(disabledforeground="#a3a3a3")
        self.UserPassword1.configure(font="TkFixedFont")
        self.UserPassword1.configure(foreground="#000000")
        self.UserPassword1.configure(insertbackground="black")

        self.UserPassword2 = tk.Entry(self.PatientRegisterFrame)
        self.UserPassword2.place(relx=0.675, rely=0.538, height=24, relwidth=0.255)
        self.UserPassword2.configure(background="white")
        self.UserPassword2.configure(disabledforeground="#a3a3a3")
        self.UserPassword2.configure(font="TkFixedFont")
        self.UserPassword2.configure(foreground="#000000")
        self.UserPassword2.configure(insertbackground="black")

        self.Password1Label = tk.Label(self.PatientRegisterFrame)
        self.Password1Label.place(relx=0.038, rely=0.525, height=34, width=92)
        self.Password1Label.configure(background="#d9d9d9")
        self.Password1Label.configure(disabledforeground="#a3a3a3")
        self.Password1Label.configure(font=font9)
        self.Password1Label.configure(foreground="#000000")
        self.Password1Label.configure(text='''Password:''')

        self.UserPassword2Label = tk.Label(self.PatientRegisterFrame)
        self.UserPassword2Label.place(relx=0.475, rely=0.525, height=34 , width=159)
        self.UserPassword2Label.configure(background="#d9d9d9")
        self.UserPassword2Label.configure(disabledforeground="#a3a3a3")
        self.UserPassword2Label.configure(font=font9)
        self.UserPassword2Label.configure(foreground="#000000")
        self.UserPassword2Label.configure(text='''Repeat password:''')
        
        ##take all string from entry
        self.UserInput["MentorID"] = self.MentorID
        self.UserInput["UserID"] = self.UserID
        self.UserInput["PatientName"] = self.PetientName
        self.UserInput["UserLastName"] = self.UserLastName
        self.UserInput["PatientDOB"] = self.PatientDOB
        self.UserInput["UserAge"] = self.UserAge
        self.UserInput["UserGender"] = self.UserGender
        self.UserInput["UserAddress"] = self.UserAddress
        self.UserInput["UserContact1"] = self.UserContact1
        self.UserInput["UserContact2"] = self.UserContact2
        self.UserInput["UserPhone"] = self.UserPhone
        self.UserInput["UserPassword1"] = self.UserPassword1
        self.UserInput["UserPassword2"] = self.UserPassword2
        self.UserInput["UserMedical"] = self.UserMedical
        self.UserInput["UserDiet"] = self.UserDiet
        
        
        
        







