#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 4.21
#  in conjunction with Tcl version 8.6
#    Mar 09, 2019 06:25:36 AM +0200  platform: Windows NT

import sys
from functools import partial
import LogicGui
import GUIandDBCommunication


try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

w = None
def create_RegisterNewMentorLevel(root, *args, **kwargs):
    '''Starting point when module is imported by another program.'''
    global w, w_win, rt
    rt = root
    w = tk.Toplevel (root)
    top = RegisterNewMentorLevel (w)
    init(w, top, *args, **kwargs)
    return (w, top)

def init(top, gui, *args, **kwargs):
    global w, top_level, root
    w = gui
    top_level = top
    root = top

def destroy_RegisterNewMentorLevel():
    global w
    w.destroy()
    w = None

class RegisterNewMentorLevel:
    def create_RegMentor(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85'
        _ana2color = '#ececec' # Closest X11 color: 'gray92'
        font10 = "-family {Segoe UI} -size 12"
        font9 = "-family {Segoe UI} -size 20 -weight bold -underline 1"  \
            ""

        top.geometry("1060x880+463+57")
        top.title("New Toplevel")
        top.configure(background="#d9d9d9")
        
        self.MentorInput= {}

        self.RegisterNewMentorFrame = tk.Frame(top)
        self.RegisterNewMentorFrame.place(relx=0.104, rely=0.034, relheight=0.909
                , relwidth=0.755)
        self.RegisterNewMentorFrame.configure(relief='groove')
        self.RegisterNewMentorFrame.configure(borderwidth="2")
        self.RegisterNewMentorFrame.configure(relief='groove')
        self.RegisterNewMentorFrame.configure(background="#d9d9d9")
        self.RegisterNewMentorFrame.configure(width=305)

        self.RegisterNewMentorLabel = tk.Label(self.RegisterNewMentorFrame)
        self.RegisterNewMentorLabel.place(relx=0.275, rely=0.025, height=51
                , width=338)
        self.RegisterNewMentorLabel.configure(background="#d9d9d9")
        self.RegisterNewMentorLabel.configure(disabledforeground="#a3a3a3")
        self.RegisterNewMentorLabel.configure(font=font9)
        self.RegisterNewMentorLabel.configure(foreground="#000000")
        self.RegisterNewMentorLabel.configure(text='''Register New Mentor''')
        
        action_with_args = partial(LogicGui.LogicGui.returnToMainFromMentor,self, top)
        
        self.NewMentorBackToMenu = tk.Button(self.RegisterNewMentorFrame, command = action_with_args)
        self.NewMentorBackToMenu.place(relx=0.1, rely=0.775, height=93
                , width=186)
        self.NewMentorBackToMenu.configure(activebackground="#ececec")
        self.NewMentorBackToMenu.configure(activeforeground="#000000")
        self.NewMentorBackToMenu.configure(background="#d9d9d9")
        self.NewMentorBackToMenu.configure(disabledforeground="#a3a3a3")
        self.NewMentorBackToMenu.configure(foreground="#000000")
        self.NewMentorBackToMenu.configure(highlightbackground="#d9d9d9")
        self.NewMentorBackToMenu.configure(highlightcolor="black")
        self.NewMentorBackToMenu.configure(pady="0")
        self.NewMentorBackToMenu.configure(text='''Back''')
        self.NewMentorBackToMenu.configure(width=186)
        
        action_with_args = partial(GUIandDBCommunication.GUIandDB.checkMentorInput, self, self.MentorInput,top,0)
        
        self.NewMentorNextToPatient = tk.Button(self.RegisterNewMentorFrame, command = action_with_args)
        self.NewMentorNextToPatient.place(relx=0.6, rely=0.763, height=103
                , width=196)
        self.NewMentorNextToPatient.configure(activebackground="#ececec")
        self.NewMentorNextToPatient.configure(activeforeground="#000000")
        self.NewMentorNextToPatient.configure(background="#d9d9d9")
        self.NewMentorNextToPatient.configure(disabledforeground="#a3a3a3")
        self.NewMentorNextToPatient.configure(foreground="#000000")
        self.NewMentorNextToPatient.configure(highlightbackground="#d9d9d9")
        self.NewMentorNextToPatient.configure(highlightcolor="black")
        self.NewMentorNextToPatient.configure(pady="0")
        self.NewMentorNextToPatient.configure(text='''Register''')
        self.NewMentorNextToPatient.configure(width=196)

        self.MentorNameLabel = tk.Label(self.RegisterNewMentorFrame)
        self.MentorNameLabel.place(relx=0.075, rely=0.15, height=34, width=62)
        self.MentorNameLabel.configure(background="#d9d9d9")
        self.MentorNameLabel.configure(disabledforeground="#a3a3a3")
        self.MentorNameLabel.configure(font=font10)
        self.MentorNameLabel.configure(foreground="#000000")
        self.MentorNameLabel.configure(text='''Name:''')

        self.MentoLastNameLabel = tk.Label(self.RegisterNewMentorFrame)
        self.MentoLastNameLabel.place(relx=0.513, rely=0.15, height=34
                , width=101)
        self.MentoLastNameLabel.configure(background="#d9d9d9")
        self.MentoLastNameLabel.configure(disabledforeground="#a3a3a3")
        self.MentoLastNameLabel.configure(font=font10)
        self.MentoLastNameLabel.configure(foreground="#000000")
        self.MentoLastNameLabel.configure(text='''Last Name:''')

        self.MentorPassword1Label = tk.Label(self.RegisterNewMentorFrame)
        self.MentorPassword1Label.place(relx=0.075, rely=0.588, height=34
                , width=92)
        self.MentorPassword1Label.configure(background="#d9d9d9")
        self.MentorPassword1Label.configure(disabledforeground="#a3a3a3")
        self.MentorPassword1Label.configure(font=font10)
        self.MentorPassword1Label.configure(foreground="#000000")
        self.MentorPassword1Label.configure(text='''Password:''')

        self.MentorPassword2Label = tk.Label(self.RegisterNewMentorFrame)
        self.MentorPassword2Label.place(relx=0.5, rely=0.588, height=34
                , width=158)
        self.MentorPassword2Label.configure(background="#d9d9d9")
        self.MentorPassword2Label.configure(disabledforeground="#a3a3a3")
        self.MentorPassword2Label.configure(font=font10)
        self.MentorPassword2Label.configure(foreground="#000000")
        self.MentorPassword2Label.configure(text='''Repeat Password:''')

        self.MentorAgeLabel = tk.Label(self.RegisterNewMentorFrame)
        self.MentorAgeLabel.place(relx=0.075, rely=0.25, height=34, width=45)
        self.MentorAgeLabel.configure(background="#d9d9d9")
        self.MentorAgeLabel.configure(disabledforeground="#a3a3a3")
        self.MentorAgeLabel.configure(font=font10)
        self.MentorAgeLabel.configure(foreground="#000000")
        self.MentorAgeLabel.configure(text='''Age:''')

        self.MentorAdresssLabel = tk.Label(self.RegisterNewMentorFrame)
        self.MentorAdresssLabel.place(relx=0.075, rely=0.35, height=34, width=80)

        self.MentorAdresssLabel.configure(background="#d9d9d9")
        self.MentorAdresssLabel.configure(disabledforeground="#a3a3a3")
        self.MentorAdresssLabel.configure(font=font10)
        self.MentorAdresssLabel.configure(foreground="#000000")
        self.MentorAdresssLabel.configure(text='''Address:''')

        self.MentorDOBLabel = tk.Label(self.RegisterNewMentorFrame)
        self.MentorDOBLabel.place(relx=0.513, rely=0.25, height=34, width=121)
        self.MentorDOBLabel.configure(background="#d9d9d9")
        self.MentorDOBLabel.configure(disabledforeground="#a3a3a3")
        self.MentorDOBLabel.configure(font=font10)
        self.MentorDOBLabel.configure(foreground="#000000")
        self.MentorDOBLabel.configure(text='''Date of birth:''')

        self.MentorPhoneLabel = tk.Label(self.RegisterNewMentorFrame)
        self.MentorPhoneLabel.place(relx=0.513, rely=0.35, height=34, width=65)
        self.MentorPhoneLabel.configure(background="#d9d9d9")
        self.MentorPhoneLabel.configure(disabledforeground="#a3a3a3")
        self.MentorPhoneLabel.configure(font=font10)
        self.MentorPhoneLabel.configure(foreground="#000000")
        self.MentorPhoneLabel.configure(text='''Phone:''')

        self.MentorIDLabel = tk.Label(self.RegisterNewMentorFrame)
        self.MentorIDLabel.place(relx=0.075, rely=0.463, height=34, width=29)
        self.MentorIDLabel.configure(background="#d9d9d9")
        self.MentorIDLabel.configure(disabledforeground="#a3a3a3")
        self.MentorIDLabel.configure(font=font10)
        self.MentorIDLabel.configure(foreground="#000000")
        self.MentorIDLabel.configure(text='''ID:''')

        self.MentorName = tk.Entry(self.RegisterNewMentorFrame)
        self.MentorName.place(relx=0.2, rely=0.163,height=24, relwidth=0.255)
        self.MentorName.configure(background="white")
        self.MentorName.configure(disabledforeground="#a3a3a3")
        self.MentorName.configure(font="TkFixedFont")
        self.MentorName.configure(foreground="#000000")
        self.MentorName.configure(insertbackground="black")

        self.MentorAge = tk.Entry(self.RegisterNewMentorFrame)
        self.MentorAge.place(relx=0.2, rely=0.263,height=24, relwidth=0.255)
        self.MentorAge.configure(background="white")
        self.MentorAge.configure(disabledforeground="#a3a3a3")
        self.MentorAge.configure(font="TkFixedFont")
        self.MentorAge.configure(foreground="#000000")
        self.MentorAge.configure(insertbackground="black")

        self.MentorAddress = tk.Entry(self.RegisterNewMentorFrame)
        self.MentorAddress.place(relx=0.2, rely=0.363, height=24, relwidth=0.255)

        self.MentorAddress.configure(background="white")
        self.MentorAddress.configure(disabledforeground="#a3a3a3")
        self.MentorAddress.configure(font="TkFixedFont")
        self.MentorAddress.configure(foreground="#000000")
        self.MentorAddress.configure(insertbackground="black")

        self.MentorID = tk.Entry(self.RegisterNewMentorFrame)
        self.MentorID.place(relx=0.2, rely=0.475,height=24, relwidth=0.255)
        self.MentorID.configure(background="white")
        self.MentorID.configure(disabledforeground="#a3a3a3")
        self.MentorID.configure(font="TkFixedFont")
        self.MentorID.configure(foreground="#000000")
        self.MentorID.configure(insertbackground="black")

        self.MentorLastName = tk.Entry(self.RegisterNewMentorFrame)
        self.MentorLastName.place(relx=0.688, rely=0.163, height=24
                , relwidth=0.255)
        self.MentorLastName.configure(background="white")
        self.MentorLastName.configure(disabledforeground="#a3a3a3")
        self.MentorLastName.configure(font="TkFixedFont")
        self.MentorLastName.configure(foreground="#000000")
        self.MentorLastName.configure(insertbackground="black")

        self.MentorDOB = tk.Entry(self.RegisterNewMentorFrame)
        self.MentorDOB.place(relx=0.688, rely=0.263,height=24, relwidth=0.255)
        self.MentorDOB.configure(background="white")
        self.MentorDOB.configure(disabledforeground="#a3a3a3")
        self.MentorDOB.configure(font="TkFixedFont")
        self.MentorDOB.configure(foreground="#000000")
        self.MentorDOB.configure(insertbackground="black")

        self.MentorPhone = tk.Entry(self.RegisterNewMentorFrame)
        self.MentorPhone.place(relx=0.688, rely=0.363, height=24, relwidth=0.255)

        self.MentorPhone.configure(background="white")
        self.MentorPhone.configure(disabledforeground="#a3a3a3")
        self.MentorPhone.configure(font="TkFixedFont")
        self.MentorPhone.configure(foreground="#000000")
        self.MentorPhone.configure(insertbackground="black")

        self.MentorPassword1 = tk.Entry(self.RegisterNewMentorFrame)
        self.MentorPassword1.place(relx=0.213, rely=0.6, height=24
                , relwidth=0.255)
        self.MentorPassword1.configure(background="white")
        self.MentorPassword1.configure(disabledforeground="#a3a3a3")
        self.MentorPassword1.configure(font="TkFixedFont")
        self.MentorPassword1.configure(foreground="#000000")
        self.MentorPassword1.configure(insertbackground="black")

        self.MentorPassword2 = tk.Entry(self.RegisterNewMentorFrame)
        self.MentorPassword2.place(relx=0.713, rely=0.6, height=24
                , relwidth=0.255)
        self.MentorPassword2.configure(background="white")
        self.MentorPassword2.configure(disabledforeground="#a3a3a3")
        self.MentorPassword2.configure(font="TkFixedFont")
        self.MentorPassword2.configure(foreground="#000000")
        self.MentorPassword2.configure(insertbackground="black")
        
        self.MentorInput["MentorName"] = self.MentorName
        self.MentorInput["MentorLastName"] = self.MentorLastName
        self.MentorInput["MentorAge"] = self.MentorAge
        self.MentorInput["MentorDOB"] = self.MentorDOB
        self.MentorInput["MentorAddress"] = self.MentorAddress
        self.MentorInput["MentorPhone"] = self.MentorPhone
        self.MentorInput["MentorID"] = self.MentorID
        self.MentorInput["MentorPassword1"] = self.MentorPassword1
        self.MentorInput["MentorPassword2"] = self.MentorPassword2






